stages:
  prepare:
    cmd: python3 src/prepare.py -d data/file1.csv data/monthly_mean.csv
  process:
    cmd: python3 src/process.py -d data/file1.csv data/computed_monthly_mean.csv
  evaluate:
    cmd: python3 src/evaluate.py -d data/computed_monthly_mean.csv -d data/monthly_mean.csv
